---
title: "Data Project Part II: Demonstrating your data skills"
author: "Student name (ID) for each member of this group"
output: pdf_document
---

## Due Dates
- Part I: Friday, February 25th, 10pm PT 
- Part II: Friday, April 1st, 10pm PT
- Part III: Monday, May 9th, 10pm PT

**Make sure to provide enough time for Gradescope submission to be uploaded if you include large visualizations.**

* Late penalty: 50% late penalty if submitted within 24 hours of due date, no 
marks for assignments submitted thereafter.

**Deliverables:**

* Submit a PDF including Parts I **and** II on Gradescope following the instructions below (one PDF per group).

**Submission Process (READ CAREFULLY):**

* Download your PDF from Datahub using the File Viewer on the bottom right panel of RStudio. (More -> Export) 
* Make sure your code does not run off the page!
* Please submit a PDF of your group project to Gradescope. When turning in each part, please submit all questions through the current part. For example, when turning in Part II, include all questions from Part I.
* Make sure to add all of your group members to the submission on Gradescope. Only one group member has to submit.
* Please answer each problem on a new page. You can specify a page break in  your Rmd using `\newpage`.
* You must indicate on Gradescope which questions are on which pages. If the page thumbnails make it difficult to see on Gradescope, open the PDF in a PDF viewer at the same time so you can make the selections accurately.
* If the submission guidelines are not followed, we may deduct points, as having to resolve individual cases creates a logistic burden on our end.

---------------------------------------------------------------------------

## Part II

In Part II of the data project, you will demonstrate a statistical concept from Part II of the course (material on midterm II, Chapters 9-12 of Baldi & Moore).

You should be using the same dataset for Part II that you used in part I.

\newpage

Questions: 

1. [1 mark] Include your work for Part I. 

2. [2 marks] Describe a quantity you will estimate as an outcome in your problem using probability notation. Are you planning to calculate marginal probabilities?  Conditional probabilities?

3. [3 marks] Describe the type of theoretical distribution that is relevant for your data.
  i) What type of variable(s) are you investigating (continuous, categorical, ordinal, etc)?  
  ii) What theoretical distribution that we have talked about would potentially be appropriate to use with these data (Normal, Binomial, Poisson...) 
  iii) Why is this an appropriate model for the data you are studying?

4. [4 marks] Use the data you have to demonstrate a statistical concept from Part II of the course. Describe the concept that you are demonstrating and interpret the findings. This may include code in R, a visual of some kind and text interpretation.  


